### ISSUE TITLE
MCP73832T-2 Battery Charger

### ISSUE THREAD

**Issue by robojay** [PaxInstruments/labwiz-board#121]
With the battery voltage divider in place, the charger will always think a battery is installed (look at the data sheet (http://ww1.microchip.com/downloads/en/DeviceDoc/20001984g.pdf) for battery detection method).  I don't think this is a problem for the current design, but something to note.

Also, the data sheet says a bypass cap should also be on the regulator's VIN (VDD) pin.  You should add one.

**Comment by charlespax** [comment]
I've added a fuel gauge. Same as in the SparkFun LiPo Fuel Gauge (https://www.sparkfun.com/products/10617).
![screen shot 2017-02-02 at 13 51 08](https://cloud.githubusercontent.com/assets/281642/22538625/c886eb2c-e94e-11e6-9457-fe8c71b19417.png)

Removed voltage divider from battery.
![screen shot 2017-02-02 at 13 51 15](https://cloud.githubusercontent.com/assets/281642/22538632/d24424ea-e94e-11e6-9c6b-5a475671ae97.png)

PC5 is now available. We could attach it to the alert interrupt of the fuel gauge, but I don't think it's worth sacrificing a pin.
