### ISSUE TITLE
Hardware for USB bootloader?

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#127]
See https://github.com/PaxInstruments/PaxInstruments-LabWiz-firmware/issues/3

**Comment by electrokean** [comment]
Maybe time to re-evaluate use of STM32F103 and use something newer like the STM32L476
Lower power, faster, better features, proper USB DFU support - but I haven't compared pinout...
Maybe check it out in STM32Cube?
There's active development for Arduino support https://github.com/GrumpyOldPizza/arduino-STM32L4

**Comment by charlespax** [comment]
I went through a bunch of chips to make sure the layout is compatible with as many chips as possible. See https://github.com/PaxInstruments/labwiz-board/issues/50. STM32L476 is not on the list, but I'm not sure why. Was that chip released after September 5th?


I just went through CubeMX and all the pin mapping appears to work out.

STM32L476:
![screen shot 2017-01-23 at 12 02 53](https://cloud.githubusercontent.com/assets/281642/22191247/eb237062-e163-11e6-91fd-e761fa767747.png)

Current LabWiz STM32F103:
![screen shot 2017-01-23 at 12 01 36](https://cloud.githubusercontent.com/assets/281642/22191248/eb5c509e-e163-11e6-9b08-7c2e16a0f46c.png)

**Comment by electrokean** [comment]
Great!  The L4 series look really nice.
I believe it was released about 12 months ago, but it may not have been added to STMCube32 till later.
I only started looking at it recently, although I'm more interested in its little brother the L432

**Comment by charlespax** [comment]
I think we're good on the bootloader hardware. Closing...
