### ISSUE TITLE
Analog reference

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#14]
What should we do with VDDA?

**Comment by charlespax** [comment]
We could leave it unconnected, butI have it connected to 3.3V. It can be completely ignored. However, it someone wants to play with using an external analog reference, there is a voltage on that pin.

![screen shot 2016-05-20 at 00 22 54](https://cloud.githubusercontent.com/assets/281642/15401198/05c7e422-1e21-11e6-994a-2153f88c7e97.png)

There is a good deal of space in the area near VDDA. We could add a footprint for a precision voltage reference and just leave it unpopulated.
![screen shot 2016-05-20 at 00 26 12](https://cloud.githubusercontent.com/assets/281642/15401382/e9111744-1e21-11e6-964b-630d8acf475c.png)

**Comment by electrokean** [comment]
Adding the ferrite in https://github.com/PaxInstruments/labwiz-board/issues/48 would allow someone to remove that and isolate VDDA to connect in an alternate reference.

**Comment by charlespax** [comment]
I like that idea. We should probably have a ferrite bead there anyway. If there's enough room, I can also add the appropriate IC footprints on the backside of the board.

An alternative approach would be to have a voltage reference on a module board. The reference can be measured by one of the GPIO pins (they all are on an ADC) for calibration of the STM32's internal reference.

**Comment by charlespax** [comment]
To keep the design simple I will not implement this. To get quality analog readings an external reference can be used to calibrate the STM32 12-bit ADC or a higher quality ADC can be connected through a digital interface. Closing issue.
