### ISSUE TITLE
MicroUSB 4-layer error

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#18]
The MicroUSB connector footprint is not 4-layer friendly. The milled holes for the legs are on the pads, which means they will be plated. The power layer is not pulled away from the milled holes. This, unfortunately, will result in the shorting of 3.3V and GND. When version 0.1.1 boards come in this area must be modified to correct this.
![screen shot 2016-05-23 at 18 33 50](https://cloud.githubusercontent.com/assets/281642/15468117/f27e24f2-2114-11e6-8d24-d27ff2fc7c30.png)

Make or find a footprint what will work with four layers.

**Comment by electrokean** [comment]
Ouch!  I'm glad I've been using drills for these mounting pins, even if soldering of them isn't quite as nice.

**Comment by charlespax** [comment]
I've added a feature to the PCB design to pull away the internal 3.3V layer. It would be nice to have this in the actual USB part, but Eagle seems to not have that ability.
![screen shot 2016-07-15 at 01 22 32](https://cloud.githubusercontent.com/assets/281642/16848930/b7e07338-4a2a-11e6-998b-346116577623.png)
