### ISSUE TITLE
SD card resistors and inductor

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#24]
Are the resistors on the SD card the correct values? We use 10k resistors.
![screen shot 2016-07-15 at 14 03 13](https://cloud.githubusercontent.com/assets/281642/16865100/e87f7042-4a94-11e6-86b6-f5d36847fdec.png)

The Olimexino board uses 100k resistors. They also use an inductor. Should we have an inductor?
![screen shot 2016-07-15 at 14 04 02](https://cloud.githubusercontent.com/assets/281642/16865135/14af0cfe-4a95-11e6-952b-3764be947b28.png)

**Comment by electrokean** [comment]
The SD card physical layer specification doesn't seem to require any pull-ups, but they're clearly a good idea to avoid floating inputs on the STM32.  I've used the Olimexino resistor configuration on my some of own designs without issue.  Interestingly I just realised I think I left them off on a recent prototype based on the STM32F103, and didn't notice any issue.
The inductor on the SD card power supply and bulk capacitance is a good idea to reduce fluctuations on the 3.3V rail during SD card operations, which can draw surges of current for short periods (write or erase).  This provides filtering for the upstream 3.3V (e.g. ADC reference) as much as for the SD card itself.
An 0805 ferrite and lower value capacitor may be OK when there is a sufficiently low impedance path from the power source, but could introduce problems when the battery is getting low, or device is powered off USB without a battery inserted, leading to data corruption or even card failure.

**Comment by charlespax** [comment]
From http://www.mikrocontroller.net/attachment/21920/SDHC_SDM04G7B7_08G7B7.pdf:
![screen shot 2016-08-23 at 13 31 00](https://cloud.githubusercontent.com/assets/281642/17881180/df1017b8-6935-11e6-864d-3d05b5adee55.png)

From https://www.kingston.com/datasheets/SDCIT-specsheet-64gb_us.pdf:
![screen shot 2016-08-23 at 14 00 26](https://cloud.githubusercontent.com/assets/281642/17881689/ff934bc8-6939-11e6-888d-44811d787963.png)

From http://www.nxp.com/documents/application_note/AN10911.pdf:
![screen shot 2016-08-23 at 13 41 31](https://cloud.githubusercontent.com/assets/281642/17881368/5fdda8d2-6937-11e6-87e5-c04e8af287dd.png)

From http://downloads.amilda.org/MODs/SDCard/SD.pdf:
![screen shot 2016-08-23 at 13 44 23](https://cloud.githubusercontent.com/assets/281642/17881411/beef3f7a-6937-11e6-8215-144ab01939ad.png)

From http://www.digitalspirit.org/file/index.php/obj-download/docs/sd/SdCard-MMC-Controller_From_Intel.pdf:
![screen shot 2016-08-23 at 14 01 57](https://cloud.githubusercontent.com/assets/281642/17881721/3936605e-693a-11e6-9ab1-8691c167a915.png)

From https://www.renesas.com/en-in/products/software-tools/software-os-middleware-driver/dsp-numerical-software/wireless-lan--rtk5563000f00000sr.html:
![screen shot 2016-08-23 at 14 02 33](https://cloud.githubusercontent.com/assets/281642/17881730/4c294c1c-693a-11e6-9db1-54f37698242c.png)

From http://www.analog.com/media/en/technical-documentation/application-notes/EE335_rev1.pdf:
![screen shot 2016-08-23 at 14 10 36](https://cloud.githubusercontent.com/assets/281642/17881890/67e71168-693b-11e6-92a9-5941a5b8d716.png)

From http://learn.parallax.com/tutorials/language/spin/propeller-board-education-project-builders/sd-card-data-storage:
![screen shot 2016-08-23 at 14 12 59](https://cloud.githubusercontent.com/assets/281642/17881934/bdbe013c-693b-11e6-81d9-5db478174cc9.png)

From http://www.lydiard.plus.com/hardware_pages/sd_card.htm:
![screen shot 2016-08-23 at 14 14 47](https://cloud.githubusercontent.com/assets/281642/17881962/fb5be360-693b-11e6-9d10-14cb6386b0a2.png)

From http://justanotherlanguage.org/content/tutorial_sd_card:
![screen shot 2016-08-23 at 14 15 18](https://cloud.githubusercontent.com/assets/281642/17881976/1821acfa-693c-11e6-915e-79f12ecccdcd.png)

See also
- http://electronics.stackexchange.com/questions/83263/micro-sd-card-power-circuit-failure

**Comment by charlespax** [comment]
Here is another reference design (http://electronics.stackexchange.com/questions/83263/micro-sd-card-power-circuit-failure).
![abv6x](https://cloud.githubusercontent.com/assets/281642/18374641/4d6d953e-7681-11e6-96f3-bb95363e19f1.jpg)

Since things are working now I'm not going to implement this in revision 0.3, but will in a future rev.

**Comment by charlespax** [comment]
I've added 10k pullups to the CMD and data lines. Caps don't seem to be very popular, so I'll just skip those.
![screen shot 2017-01-28 at 13 26 16](https://cloud.githubusercontent.com/assets/281642/22394474/6257a610-e55d-11e6-8f29-da2ef6f7f5da.png)
![screen shot 2017-01-28 at 13 26 22](https://cloud.githubusercontent.com/assets/281642/22394475/625d2a9a-e55d-11e6-930a-981bc83c72ba.png)
