### ISSUE TITLE
Serial port connections

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#26]
Do we need pullup resistors on the serial lines? Possibly so for the bootloader. See [AN2606 p. 26](http://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf).
![screen shot 2016-07-15 at 23 36 15](https://cloud.githubusercontent.com/assets/281642/16879831/f3b686f8-4ae4-11e6-95e7-636c721567b5.png)

**Comment by electrokean** [comment]
Always want one on the Rx pin at each device that may have its input disconnected from the transmitter

**Comment by charlespax** [comment]
Done

**Comment by charlespax** [comment]
The resistors were removed at some point. I'm adding them again.
![screen shot 2017-01-23 at 12 53 29](https://cloud.githubusercontent.com/assets/281642/22191981/fc10d6e2-e16a-11e6-9a32-ddf95746cb7d.png)

**Comment by charlespax** [comment]
Added back on the board.

![screen shot 2017-01-23 at 13 00 40](https://cloud.githubusercontent.com/assets/281642/22192112/02258964-e16c-11e6-9795-967e770ed0b2.png)
![screen shot 2017-01-23 at 13 00 50](https://cloud.githubusercontent.com/assets/281642/22192113/0226c158-e16c-11e6-8af1-0b692388413e.png)
