### ISSUE TITLE
USB connection for bootloader

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#27]
What do we need for enabling the bootloader to flash over USB? See [AN2606 p. 26](http://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf).
![screen shot 2016-07-15 at 23 38 52](https://cloud.githubusercontent.com/assets/281642/16879961/73990684-4ae5-11e6-878e-00867322499d.png)

**Comment by electrokean** [comment]
STM32F103 doesn't have built in USB DFU bootloader, so it would be dependant on a separate bootloader like https://github.com/rogerclarkmelbourne/STM32duino-bootloader
See the notes there in README.md as there are a few implementation options for the disconnect feature

**Comment by charlespax** [comment]
Moved to firmware repo.

**Comment by electrokean** [comment]
For the more modern chips with USB DFU, you should just need a way to control BOOT0 (and possibly RESET) to start the bootloader.

If you have a spare I/O pin, you can do a nifty firmware trick by connecting that to BOOT0 along with a small capacitor.  To enter the bootloader, the firmware pulls the I/O pin high to charge the cap, and then does a reset while the cap holds BOOT0 high (slowly discharging through a pulldown).

Ref: http://stackoverflow.com/questions/26891432/jump-to-bootloader-in-stm32-through-appliction-i-e-using-boot-0-and-boot-1-pins

**Comment by charlespax** [comment]
PC1 is currently not used and is a good candidate. It could easily be routed over.
![screen shot 2017-01-23 at 13 16 32](https://cloud.githubusercontent.com/assets/281642/22192346/40de1192-e16e-11e6-9fae-827ebc693e36.png)

I think this circuit would work. I would just connect PC1 to BOOT0 and add a cap across the 10k pulldown resistor. Not sure what value.
![img_20170123_131758](https://cloud.githubusercontent.com/assets/281642/22192399/be42f8aa-e16e-11e6-95e0-ccfc82973b9b.jpg)

I would have to change the BOOT1 circuit. Right now it's normally high, which would make the device boot from SRAM. Making BOOT1 normally low would have the system default to system memory (hardware bootloader) if BOOT0 is high.
![screen shot 2017-01-23 at 13 24 01](https://cloud.githubusercontent.com/assets/281642/22192449/3dcadb1a-e16f-11e6-9a2e-6b55fd1b057c.png)

![screen shot 2017-01-23 at 13 27 06](https://cloud.githubusercontent.com/assets/281642/22192517/b196925a-e16f-11e6-89bf-081db054c512.png)

**Comment by charlespax** [comment]
Since at lease some chips require a 1.5k pullup on USB_DP, we should implement the circuit. Here is an except from [AN2606](http://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf)
![screen shot 2017-01-23 at 13 42 05](https://cloud.githubusercontent.com/assets/281642/22192776/c0c8e244-e171-11e6-8b3b-8cf3053b5231.png)

**Comment by charlespax** [comment]
Actually, the board already has the 1.5K pullup. I think the pullup is to indicate to the host if the device is full-speed or high-speed (see also #55 ).
![screen shot 2017-01-23 at 13 44 17](https://cloud.githubusercontent.com/assets/281642/22192806/0e753a60-e172-11e6-95f4-8a56b8982c44.png)

**Comment by charlespax** [comment]
Yes, the 1.5k pullup on DP is to indicate full-speed. It is also the same circuit to indicate high-speed.

Change made to the BOOT1 switch.
![screen shot 2017-01-23 at 14 00 06](https://cloud.githubusercontent.com/assets/281642/22193124/46fd9826-e174-11e6-9624-f76dbf3e4171.png)

PC1 connected to BOOT0.
![screen shot 2017-01-23 at 14 03 46](https://cloud.githubusercontent.com/assets/281642/22193256/0ada25fc-e175-11e6-9e5d-3c3f8b51a129.png)

Capacitor added in parallel with the BOOT0 pulldown.
![screen shot 2017-01-23 at 14 05 07](https://cloud.githubusercontent.com/assets/281642/22193265/1b9a8b66-e175-11e6-8124-e3489197fc33.png)

**Comment by charlespax** [comment]
Done. Closing issue.
