### ISSUE TITLE
Oscillator component choice

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#31]
In the design I've made the assumption that the main oscillator and the RTC oscillator are available in the same footprint. I have to verify this or possibly change to parts that actually exist and are available.

![screen shot 2016-07-22 at 17 37 55](https://cloud.githubusercontent.com/assets/281642/17053118/0d1e6964-5033-11e6-9c11-827396f999f6.png)

**Comment by electrokean** [comment]
Yeah, this is probably not the case.
The RTC crystal specs can be quite particular around capacitance and ESR.
Check out AN2867 - it has lots of info plus lists of some suggested parts, and it will also point out some potential issues with your layout around that area.
Finding parts that meets your price/footprint/availability requirements can be a bit of a challenge.

**Comment by charlespax** [comment]
It looks like small 8 MHz crystals are pretty easy and cheap to get. A small 16 MHz device would have to be a more expensive and rare MEMS device. We'll go with 8 MHz.

Here is a commonly available component from the HQB market. When buying twenty pieces I paid 2 RMB each.
![micromsg 1470640641119](https://cloud.githubusercontent.com/assets/281642/17472544/11711d4c-5d7e-11e6-94bf-4548d30d2370.jpg)
Datasheet: http://www.ndk.com/images/products/catalog/c_NX3225GD-STD-CRA-3_e.pdf
![screen shot 2016-08-08 at 16 34 40](https://cloud.githubusercontent.com/assets/281642/17473986/230cfd5c-5d86-11e6-8c59-e5e000eeb5a6.png)

**Comment by charlespax** [comment]
Here is the new crystal on the PCB. ![screen shot 2016-08-08 at 21 43 37](https://cloud.githubusercontent.com/assets/281642/17481742/318967aa-5db1-11e6-9689-93e465903e0a.png)
