### ISSUE TITLE
Purpose of VBUS input

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#39]
We have VBUS input on PA9, but I'm not sure why. We're pretty strapped for pins, so it would be nice to know if we can repurpose this pin. What is the use case here?
![screen shot 2016-08-09 at 01 06 21](https://cloud.githubusercontent.com/assets/281642/17488778/8422073a-5dcd-11e6-83e3-c502ee1a80b1.png)

**Comment by electrokean** [comment]
I'm guessing this is useful for knowing when a USB cable is plugged in - either for mcu based battery charger control or to begin USB enumeration.  Most pins are 5V tolerant, but I still tend to include a resistive divider myself...

**Comment by charlespax** [comment]
The USB data lines handle enumeration. I've removed and repurposed the VBUS line as the VBAT_DIV2 battery voltage input.
