### ISSUE TITLE
ESP8266 connections

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#41]
A header is on the board for an ESP8266 module, which runs on USART1. I need to review and implement any necessary pullups/pulldowns and any other components necessary.
![screen shot 2016-08-15 at 10 43 44](https://cloud.githubusercontent.com/assets/281642/17654376/26e1e330-62d5-11e6-850b-11cf1513fe1a.png)
![screen shot 2016-08-15 at 10 43 57](https://cloud.githubusercontent.com/assets/281642/17654380/2ec72bbe-62d5-11e6-9028-65f4d2bfd7c3.png)
![screen shot 2016-08-15 at 10 56 23](https://cloud.githubusercontent.com/assets/281642/17654562/f3c3269c-62d6-11e6-91f5-ff1731e0c369.png)

**Comment by charlespax** [comment]
I dropped a 10 uF cap on the power lines. Everything else seems to be in order.
![screen shot 2016-08-15 at 11 51 17](https://cloud.githubusercontent.com/assets/281642/17655483/6b493fbc-62e1-11e6-9f36-6751709db323.png)

**Comment by charlespax** [comment]
Done. Looks good.

**Comment by charlespax** [comment]
WIFI now has a dedicated USART. Review connections again.

**Comment by samchoy88** [comment]
Using USART3 right now
![image](https://cloud.githubusercontent.com/assets/1327611/21074401/1405fa7a-bf33-11e6-8e4a-e00dafd512e1.png)
