### ISSUE TITLE
Power output

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#42]
I want the board to be able to output as much power as possible. I may need to select another 3.3V regulator.
- What can we draw from the battery?
- What can the 3.3V regulator output?

**Comment by electrokean** [comment]
If you gave up one of the ground pins on the modules, you could route VBAT or VBUS to them.

Or just allow for a pad on one of these for people wanting to hack to easily wire a jumper across to a module.

**Comment by charlespax** [comment]
It turns out the CAN and USB use the same memory and cannot be used together. Thus, I'm dropping CAN from the interface. Not a big deal. This frees up two pins. The fourteen pin connector will have the following pins.
- 3V3
- 3V3
- VBUS
- GND
- GND
- SPI_MISO
- SPI_MOSI
- SPI_SCK
- GPIO1
- GPIO2
- USART_RX
- USART_TX
- I2C_SD
- I2C_SCL

With the addition of VBUS to the module a design could draw directly from USB power or from the battery. Anything beyond that and a design could have an independent power input.

**Comment by charlespax** [comment]
Each connector has a pin for VBUS. Closing issue.
