### ISSUE TITLE
4.7 uF cap

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#45]
The stm32f103 datasheet indicates Vdd3 needs a 4.7 uF cap.
![screen shot 2016-08-18 at 00 01 23](https://cloud.githubusercontent.com/assets/281642/17743635/f6e7fb34-64d6-11e6-8a37-a02c9e54e286.png)

**Comment by charlespax** [comment]
I've added the 4.7 uF cap.
![screen shot 2016-08-20 at 21 43 13](https://cloud.githubusercontent.com/assets/281642/17831578/2052b564-671f-11e6-9e00-9c1b9117e065.png)

It also looks like I can remove all the 10 uF caps and change the VDDA cap from on 100 nF to one 10 nF cap and one 1 uF cap.
![screen shot 2016-08-20 at 21 45 05](https://cloud.githubusercontent.com/assets/281642/17831589/612a84e0-671f-11e6-8055-7ec1c7b96bbe.png)

**Comment by charlespax** [comment]
Removed 10uF caps on VDD pins. Changed VDDA caps.
![screen shot 2016-08-22 at 21 29 00](https://cloud.githubusercontent.com/assets/281642/17856322/80ce6c76-68af-11e6-88df-f77e5acdacc3.png)

**Comment by electrokean** [comment]
Maybe add a small ferrite bead or low value resistor between VDD and VDDA to filter noise from CPU core?

**Comment by charlespax** [comment]
Good call. I've opened an issue. https://github.com/PaxInstruments/labwiz-board/issues/48
