### ISSUE TITLE
STM32 LQFP64 compatability

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#50]
One of the nicest aspects of the STM32 family is that the chips are very compatible. If we carefully select the peripheral pin mapping, switching between chips will be relatively trivial.

Here is how pins are mapped in LabWiz v0.2. 
![screen shot 2016-09-03 at 13 31 35](https://cloud.githubusercontent.com/assets/281642/18222973/c9617cba-71da-11e6-85d1-068d0f01d247.png)

If we change to this pin map, we can swap out the stm32f103rgt (1024k flash, 96k RAM) with the stm32f412rgt (1024k flash,256k RAM).
![screen shot 2016-09-03 at 13 29 43](https://cloud.githubusercontent.com/assets/281642/18222967/84e39122-71da-11e6-831f-f9603eee7bd6.png)

Here is the stm32f412.
![screen shot 2016-09-03 at 13 30 55](https://cloud.githubusercontent.com/assets/281642/18222982/3fd0cc98-71db-11e6-80eb-84e604077190.png)

The downside of implementing this configuration is that we lose a bit of interface flexibility with the modules. The LabWiz v0.2 design gives two USART, two SPI, and two i2c. The compatibility configuration would give two USART, two SPI, and one i2c. Since i2c is a multi-device bus, this isn't much of an issue.

**Comment by charlespax** [comment]
Here's what I have right now. The unassigned pins would be for the six GPIO pins for the modules. The two SPI_NSS pins plus the six GPIO are the eight GPIO pins required by the interface.

![screen shot 2016-09-03 at 20 26 33](https://cloud.githubusercontent.com/assets/281642/18224814/d4eccd0c-7214-11e6-9603-aae227c5260e.png)

PA10 is unused in this design and is reserved and would be used for USB_OTG if the stm32f412 were used. PB11 is also not used. The stm32f412 uses this pin for a power capacitor. That is also what compelled the decision or use only a single I2C interface.

Board routing looks like it is going to shake out much better.
![screen shot 2016-09-03 at 20 31 41](https://cloud.githubusercontent.com/assets/281642/18224825/756d1304-7215-11e6-826d-34df08d0f54b.png)

**Comment by electrokean** [comment]
Out of interest, what did you use to generate those pinout images?

**Comment by charlespax** [comment]
I used [STM32CubeMX](http://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-configurators-and-code-generators/stm32cubemx.html) from ST. It's a super flipping awesome GUI for defining all the pins and peripherals.

![screen shot 2016-09-03 at 21 23 56](https://cloud.githubusercontent.com/assets/281642/18225061/c62a68d0-721c-11e6-8ae8-158692319e4f.png)

It will help define all the timing.
![screen shot 2016-09-03 at 21 24 09](https://cloud.githubusercontent.com/assets/281642/18225060/c6249d9c-721c-11e6-8508-51e9c2199cce.png)

Then it will generate all the startup code in a project. It supports several IDEs. We've been using a secondary Python script to translate from SW4STM32 to and Eclipse project.
![screen shot 2016-09-03 at 21 26 54](https://cloud.githubusercontent.com/assets/281642/18225082/2b9e57c6-721d-11e6-80c2-0baa1e7d3e57.png)

**Comment by electrokean** [comment]
Thanks @charlespax. I suspected it was from STMCube.  I played with an older version, but only briefly.  I have been writing my own startup code so far.  Will have to try this latest version out, especially with PCBs for a new design about to land.

**Comment by charlespax** [comment]
Given the following criteria,
- STM32 family
- LQFP64 package
- Have USB capability
- Have SDIO interface

The following twenty-seven parts are potentially compatible.
- STM32F103RC
- STM32F103RD
- STM32F103RE
- STM32F103RF
- STM32F103RG
- STM32F205RB
- STM32F205RC
- STM32F205RE
- STM32F205RF
- STM32F205RG
- STM32F215RE
- STM32F215RG
- STM32F401RB
- STM32F401RC
- STM32F401RD
- STM32F401RE
- STM32F405RG
- STM32F411RC
- STM32F411RE
- STM32F412RE
- STM32F412RG
- STM32F415RG
- STM32F446RC
- STM32F446RE
- STM32L151RD
- STM32L152RD
- STM32L162RD

There are a few down sides with taking SDIO as a criteria. The chip with the lowest amount of flash has 128k flash, 64k RAM. That's fine for development, but limits the options for reducing cost in a final product. However, if we were to use a SPI interface instead, we will be compatible with sixty chips. We'd would then only have one SPI interface for all four modules. Not a good trade off.

**Comment by charlespax** [comment]
Here's where I am.

![screen shot 2016-09-05 at 17 47 37](https://cloud.githubusercontent.com/assets/281642/18244102/e6de3a82-7390-11e6-9e84-d4c5b4bc03a2.png)

All module GPIO pins are capable of GPIO, external interrupt, and 12-bit ADC measurements. Additional features are carried on the pins as listed below.
- MOD1_GPIO1 SPI1_NSS, DAC_OUT1
- MOD1_GPIO2 PWM
- MOD2_GPIO1 GPIO PWM
- MOD3_GPIO1 SPI2_NSS

**Comment by charlespax** [comment]
I've routed a new board revision. Closing this issue.

![screen shot 2016-09-09 at 11 17 49](https://cloud.githubusercontent.com/assets/281642/18374396/1354f93e-767f-11e6-93c7-1757d64e13a2.png)
