### ISSUE TITLE
USB power protection

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#59]
What protection is needed on the USB power? Right now it's connected directly to VBUS.

**Comment by robojay** [comment]
Add a PTC resettable fuse between the USB connector VCC pin and VBUS.

I've used Bel Fuse 0ZCJ0050FF2G (Digi-Key 507-1802-1-ND) in similar applications.

**Comment by robojay** [comment]
Add a transient voltage suppressor between VUSB and ground.  Something like SMBJ5.0A will work.

**Comment by charlespax** [comment]
I've added a PTC resettable fuse. I'm going for the 0805 package because that fits best on the board.  This part seems good: http://www.digikey.com/product-detail/en/bel-fuse-inc/0ZCK0050FF2E/507-1813-2-ND/4156141
![screen shot 2017-01-23 at 11 21 12](https://cloud.githubusercontent.com/assets/281642/22190535/c628a480-e15e-11e6-8fc0-555f8337dcbb.png)
![screen shot 2017-01-23 at 11 21 18](https://cloud.githubusercontent.com/assets/281642/22190536/c65b8166-e15e-11e6-8d2a-8b9efb338274.png)

**Comment by charlespax** [comment]
I've added a transient voltage suppressor to USB_VBUS. It's the same as what I have on the data lines (PGB1010603).

![screen shot 2017-01-23 at 11 40 29](https://cloud.githubusercontent.com/assets/281642/22190786/d0953094-e160-11e6-8d83-a203e5d7a868.png)
![screen shot 2017-01-23 at 11 40 47](https://cloud.githubusercontent.com/assets/281642/22190787/d0a6f68a-e160-11e6-8d50-936c6413ea98.png)
