### ISSUE TITLE
I2c pull up resistors

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/labwiz-board#67]
Redo calculations and find what would be a good value. Can we even have a fixed value without knowing the total capacitance on the lines?

We could go nuts and use digital pots.

**Comment by charlespax** [comment]
Dupe of https://github.com/PaxInstruments/labwiz-board/issues/67

**Comment by electrokean** [comment]
Dupe of itself?

**Comment by charlespax** [comment]
hahahaha Dupe of #68
